### ISSUE TITLE
Нет оформленной лицензии

### ISSUE THREAD

**Issue by asmfreak** [kkirsanov/sensorika-robot#4]
Надо бы добавить лицензию, чтобы можно было без неудоств показывать и ссылаться на этот код.

**Comment by kkirsanov** [comment]
LGPL?

**Comment by asmfreak** [comment]
v2 или v3?
https://hsto.org/storage/fb8c664b/b7867fcd/5544e4b6/fa7b6937.png

**Comment by kkirsanov** [comment]
двай 3
